export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const ADMIN_LOADED = 'ADMIN_LOADED'
export const ADMIN_ERROR = 'ADMIN_ERROR'
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const LOGOUT = 'LOGOUT'
