export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const ADMIN_LOADED = 'ADMIN_LOADED'
export const ADMIN_ERROR = 'ADMIN_ERROR'
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const LOGOUT = 'LOGOUT'

export const CREATE_PROVIDER = 'CREATE_PROVIDER'
export const CREATE_PROVIDER_ERROR = 'CREATE_PROVIDER_ERROR'
export const GET_PROVIDERS = 'GET_PROVIDERS'
export const GET_PROVIDERS_ERROR = 'GET_PROVIDERS_ERROR'
export const GET_PROVIDER = 'GET_PROVIDER'
export const GET_PROVIDER_ERROR = 'GET_PROVIDER_ERROR'
export const UPDATE_PROVIDER = 'UPDATE_PROVIDER'
export const UPDATE_PROVIDER_ERROR = 'UPDATE_PROVIDER_ERROR'
export const DELETE_PROVIDER = 'DELETE_PROVIDER'
export const DELETE_PROVIDER_ERROR = 'DELETE_PROVIDER_ERROR'

export const CREATE_PAKET = 'CREATE_PAKET'
export const CREATE_PAKET_ERROR = 'CREATE_PAKET_ERROR'

export const GET_PAKETS = 'GET_PAKETS'
export const GET_PAKETS_ERROR = 'GET_PAKETS_ERROR'

export const GET_PAKET = 'GET_PAKET'
export const GET_PAKET_ERROR = 'GET_PAKET_ERROR'

export const UPDATE_PAKET = 'UPDATE_PAKET'
export const UPDATE_PAKET_ERROR = 'UPDATE_PAKET_ERROR'

export const DELETE_PAKET = 'DELETE_PAKET'
export const DELETE_PAKET_ERROR = 'DELETE_PAKET_ERROR'

export const GET_TRANSACTIONS = 'GET_TRANSACTIONS'
export const GET_TRANSACTIONS_ERROR = 'GET_TRANSACTIONS_ERROR'

export const CREATE_TRANSACTION = 'CREATE_TRANSACTION'
export const CREATE_TRANSACTION_ERROR = 'CREATE_TRANSACTION_ERROR'

export const DELETE_TRANSACTION = 'DELETE_TRANSACTION'
export const DELETE_TRANSACTION_ERROR = 'DELETE_TRANSACTION_ERROR'

export const DELETE_ALL_TRANSACTIONS = 'DELETE_ALL_TRANSACTIONS'
export const DELETE_ALL_TRANSACTIONS_ERROR = 'DELETE_ALL_TRANSACTIONS_ERROR'

export const GET_TRANSFERS = 'GET_TRANSFERS'
export const GET_TRANSFERS_ERROR = 'GET_TRANSFERS_ERROR'

export const CREATE_TRANSFER = 'CREATE_TRANSFER'
export const CREATE_TRANSFER_ERROR = 'CREATE_TRANSFER_ERROR'

export const DELETE_TRANSFER = 'DELETE_TRANSFER'
export const DELETE_TRANSFER_ERROR = 'DELETE_TRANSFER_ERROR'

export const DELETE_ALL_TRANSFERS = 'DELETE_ALL_TRANSFERS'
export const DELETE_ALL_TRANSFERS_ERROR = 'DELETE_ALL_TRANSFERS_ERROR'
